import type { workout_catalogue } from "@prisma/client";

export function serializeCatalogueWorkout(row: workout_catalogue) {
  return {
    id: row.id,
    name: row.name,
    slug: row.slug,
    description: row.description,
    workoutType: row.workoutType,
    runSubType: row.runSubType,
    segmentPaceDist: row.segmentPaceDist,
    warmupFraction: row.warmupFraction,
    workFraction: row.workFraction,
    cooldownFraction: row.cooldownFraction,
    workBaseReps: row.workBaseReps,
    workBaseRepMeters: row.workBaseRepMeters,
    recoveryDistanceMeters: row.recoveryDistanceMeters,
    recoveryDurationSeconds: row.recoveryDurationSeconds,
    warmupMiles: row.warmupMiles,
    warmupPaceOffsetSecPerMile: row.warmupPaceOffsetSecPerMile,
    cooldownMiles: row.cooldownMiles,
    cooldownPaceOffsetSecPerMile: row.cooldownPaceOffsetSecPerMile,
    workBaseMiles: row.workBaseMiles,
    workPaceOffsetSecPerMile: row.workPaceOffsetSecPerMile,
    workBasePaceOffsetSecPerMile: row.workBasePaceOffsetSecPerMile,
    recoveryPaceOffsetSecPerMile: row.recoveryPaceOffsetSecPerMile,
    paceAnchor: row.paceAnchor,
    mpFraction: row.mpFraction,
    mpBlockPosition: row.mpBlockPosition,
    mpBlockProgression: row.mpBlockProgression,
    mpTotalMiles: row.mpTotalMiles,
    mpPaceOffsetSecPerMile: row.mpPaceOffsetSecPerMile,
    intendedHeartRateZone: row.intendedHeartRateZone,
    intendedHRBpmLow: row.intendedHRBpmLow,
    intendedHRBpmHigh: row.intendedHRBpmHigh,
    notes: row.notes,
    trainingIntent: row.trainingIntent,
    createdAt: row.createdAt,
    updatedAt: row.updatedAt,
  };
}
